# Generated by Django 3.0.3 on 2020-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=1000)),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
    ]
